# Generated by Django 2.1.7 on 2021-01-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='uprofile',
            fields=[
                ('Uid', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('hname', models.CharField(max_length=100)),
                ('cname', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('uname', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('Ename', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('Status', models.CharField(default='active', max_length=20)),
            ],
        ),
    ]
