# Generated by Django 2.1.7 on 2021-01-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_uprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uprofile',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
