# Generated by Django 2.1.7 on 2021-01-13 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_auto_20210113_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='opday',
            fields=[
                ('Did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app2.dprofile', unique=True)),
                ('sun', models.IntegerField()),
                ('mon', models.IntegerField()),
                ('tue', models.IntegerField()),
                ('wed', models.IntegerField()),
                ('thu', models.IntegerField()),
                ('fri', models.IntegerField()),
                ('sat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='optime',
            fields=[
                ('Did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app2.dprofile', unique=True)),
                ('opfrom', models.TimeField()),
                ('opto', models.TimeField()),
            ],
        ),
    ]
