# Generated by Django 2.1.7 on 2021-02-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_auto_20210208_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='medHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('bg', models.CharField(max_length=10)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('medication', models.CharField(default='no', max_length=10)),
                ('medlist', models.CharField(default='nil', max_length=200)),
                ('mallergy', models.CharField(default='no', max_length=10)),
                ('allergylist', models.CharField(default='nil', max_length=200)),
                ('tob', models.CharField(max_length=10)),
                ('alco', models.CharField(max_length=10)),
            ],
        ),
    ]
