# Generated by Django 2.1.7 on 2021-03-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_medhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medhistory',
            old_name='uid',
            new_name='Uid',
        ),
    ]
