# Generated by Django 2.1.7 on 2021-03-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_auto_20210321_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medhistory',
            old_name='Uid',
            new_name='uid',
        ),
    ]
